classes:
- system.linux.system.repo.mcp.salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.master.api
- system.salt.minion.ca.salt_master
- system.reclass.storage.salt
- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_proxy_cluster
- system.reclass.storage.system.openstack_gateway_cluster
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- system.reclass.storage.system.openstack_telemetry_cluster
#- system.reclass.storage.system.stacklight_log_cluster
#- system.reclass.storage.system.stacklight_monitor_cluster
#- system.reclass.storage.system.stacklight_telemetry_cluster
- cluster.physical_mcp11_ovs_dpdk
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: https://github.com/sgudz/mcp11_ovs_dpdk.git
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    salt_master_host: ${_param:infra_config_address}
    salt_api_password_hash: "$6$sGnRlxGf$al5jMCetLP.vfI/fTl3Z0N7Za1aeiexL487jAtyRABVfT3NlwZxQGVhO7S1N8OwS/34VHYwZQA8lkXwKMN/GS1"
  salt:
    master:
      accept_policy: open_mode
  reclass:
    storage:
      node:
        infra_kvm_node01:
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
        infra_kvm_node02:
          params:
            keepalived_vip_priority: 101
            linux_system_codename: xenial
            deploy_nic: enp9s0f0
        infra_kvm_node03:
          params:
            keepalived_vip_priority: 102
            linux_system_codename: xenial
            deploy_nic: enp11s0f0
        openstack_gateway_node01:
          params:
            deploy_address: ${_param:openstack_gateway_node01_deploy_address}
        openstack_gateway_node02:
          params:
            deploy_address: ${_param:openstack_gateway_node02_deploy_address}
        openstack_telemetry_node01:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 100
        openstack_telemetry_node02:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 101
        openstack_telemetry_node03:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 102
        openstack_proxy_node01:
          params:
            linux_system_codename: xenial
        openstack_proxy_node02:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node01:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node02:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node03:
          params:
            linux_system_codename: xenial
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
          params:
            linux_system_codename: xenial
#          parameters:
#            avinetworks:
#              server:
#                enabled: true
#                identity: cloud1
#                image_location: http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
#                disk_format: qcow2
#                public_network: floating
#                saltmaster_ip: 172.16.52.117
#            keystone:
#              client:
#                enabled: true
#                server:
#                  cloud1:
#                    admin:
#                      host: 10.167.4.10 #${_param:keystone_service_host}
#                      port: 5000
#                      project: admin
#                      user: admin
#                      password: password
#                      protocol: http
#                      region_name: RegionOne
        openstack_control_node02:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
          params:
            linux_system_codename: xenial
        openstack_control_node03:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
          params:
            linux_system_codename: xenial
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
          params:
            linux_system_codename: xenial
        openstack_database_node02:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
          params:
            linux_system_codename: xenial
        openstack_database_node03:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
          params:
            linux_system_codename: xenial


        openstack_compute_node01:
          name: ${_param:openstack_compute_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            control_address: ${_param:openstack_compute_node01_control_address}
            single_address: ${_param:openstack_compute_node01_single_address}
            tenant_address: ${_param:openstack_compute_node01_tenant_address}
            dpdk0_pci: '"0000:81:00.0"'
            dpdk1_pci: '"0000:81:00.1"'
        openstack_compute_node02:
          name: ${_param:openstack_compute_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            control_address: ${_param:openstack_compute_node02_control_address}
            single_address: ${_param:openstack_compute_node02_single_address}
            tenant_address: ${_param:openstack_compute_node02_tenant_address}
            dpdk0_pci: '"0000:81:00.0"'
            dpdk1_pci: '"0000:81:00.1"'
